Repository Real-Dev-Squad/discord-slash-commands, pull requests merged in 2023-03, with the labels that each got.

#38 Added environment name
  .github/workflows/register-commands-production.yaml
  .github/workflows/register-commands-staging.yaml
Labels: enhancement

#40 Environment setup
  config/config.ts
  src/constants/urls.ts
  src/typeDefinitions/default.types.d.ts
  tests/fixtures/config.ts
  tests/unit/config/config.test.ts
Labels: DX

#35 add a utility which when called upon changes nickname
  .github/workflows/register-commands-production.yaml
  .github/workflows/register-commands-staging.yaml
  src/constants/responses.ts
  src/utils/updateNickname.ts
Labels: feature task

#34 Store Discord User Data in RDS Backend
  .github/workflows/register-commands-production.yaml
  .github/workflows/register-commands-staging.yaml
  package-lock.json
  package.json
  src/constants/urls.ts
  src/controllers/baseHandler.ts
  src/controllers/verifyCommand.ts
  src/typeDefinitions/discordMessage.types.d.ts
  src/utils/sendUserDiscordData.ts
  tests/fixtures/fixture.ts
  wrangler.toml
Labels: feature task

#46 add account-id
  .github/workflows/register-commands-production.yaml
  .github/workflows/register-commands-staging.yaml
Labels: refactor
